---
- hosts: all
  remote_user: ubuntu
  become: true
  become_method: sudo
  
  tasks:  
    - name: Clone tower-base into configured directory.
      git:
        repo: https://github.com/mejs123/tower-base.git
        dest: "/home/ubuntu/tower-base"
        #version: master
        #update: yes
        #accept_hostkey: yes
        force: yes

    - name: Install ansible-container[docker]
      pip: name=ansible-container[docker]==0.9.2
    
   
    - name: Run ansible_galaxy install
      command: "ansible-galaxy -r install requirements.yml"
      args:
        chdir: "/home/ubuntu/tower-base/containers"

    - name: Run ansible-container playbook
      command: "ansible-container run"
      args:
        chdir: "/home/ubuntu/tower-base/containers"

    - name: Run ansible-container playbook
      command: "ansible-container build"
      args:
        chdir: "/home/ubuntu/tower-base/containers"
