---
- hosts: all
  remote_user: ubuntu
  become: true
  become_method: sudo

  roles:
    - { role: geerlingguy.docker }
    - { role: rfhayashi.ansible-container }

- include: container_install.yml

