---
- hosts: all
  user: ubuntu
  become: true
  become_method: sudo

  vars:
    nodejs_version: "6.x"
    pip_install_packages:
      - name: docker-py

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
          #- name: geerlingguy.repo-epel
          #when: ansible_os_family == "RedHat"
    - { role: geerlingguy.git }
    - { role: geerlingguy.ansible }
    - { role: geerlingguy.docker }
    - { role:geerlingguy.pip }
    - { role: geerlingguy.nodejs }
    - { role: ansible-role-awx }
