---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
  - name: Download Vagrancy 
    get_url:
      url: https://github.com/ryandoyle/vagrancy/releases/download/0.0.4/vagrancy-0.0.4-linux-x86_64.tar.gz 
      dest: /home/ubuntu/vagrancy-0.0.4-linux-x86_64.tar.gz
  
  - name: Extract Vagrancy
    unarchive:
      src: vagrancy-0.0.4-linux-x86_64.tar.gz
      dest: /home/ubuntu/

  - name: Run Vagrancy
    shell: /home/ubuntu/vagrancy-0.0.4-linux-x86_64/vagrancy
    async: 2592000
    poll: 0
